# source https://digilent.com/reference/pmod/pmodjstk2/reference-manual?redirect=1
# Contants commnds to use spi

CMD_DEFAULT = [0x00]

# Get Commands
CMD_GET_POSITION = [0xC0]
CMD_GET_STATUS = [0xF0]
CMD_GET_FIRMWARE_VER = [0xF1]
CMD_GET_CAL_X_MIN = [0xE0]
CMD_GET_CAL_X_MAX = [0xE1]
CMD_GET_CAL_Y_MIN = [0xE2]
CMD_GET_CAL_Y_MAX = [0xE3]
CMD_GET_CAL_X_CEN_MIN = [0xE4]
CMD_GET_CAL_X_CEN_MAX = [0xE5]
CMD_GET_CAL_Y_CEN_MIN = [0xE6]
CMD_GET_CAL_Y_CEN_MAX = [0xE7]

# Set Commands
CMD_SET_LED = [0x80]
CMD_SET_LED_RGB = [0x84]
CMD_SET_INVERSION = [0x88]
CMD_SET_CAL_X_MIN = [0xA8]
CMD_SET_CAL_X_MAX = [0xA9]
CMD_SET_CAL_Y_MIN = [0xAA]
CMD_SET_CAL_Y_MAX = [0xAB]
CMD_SET_CAL_X_CEN_MIN = [0xAC]
CMD_SET_CAL_X_CEN_MAX = [0xAD]
CMD_SET_CAL_Y_CEN_MIN = [0xAE]
CMD_SET_CAL_Y_CEN_MAX = [0xAF]
CMD_SET_CAL_X_MIN_MAX = [0xB0]
CMD_SET_CAL_Y_MIN_MAX = [0xB1]
CMD_SET_CAL_X_CEN_MIN_MAX = [0xB2]
CMD_SET_CAL_Y_CEN_MIN_MAX = [0xB3]

# Other Commands
CMD_CALIBRATE = [0xA4]
CMD_WRITE_FLASH = [0xB8]
CMD_RLD_FROM_FLASH = [0xBC]
